import type { User, Coupon, Chat } from './definitions';
import { subDays, formatISO } from 'date-fns';

export const users: User[] = [
  { id: 'user-1', username: 'Alice', avatarUrl: 'https://i.pravatar.cc/150?u=user-1' },
  { id: 'user-2', username: 'Bob', avatarUrl: 'https://i.pravatar.cc/150?u=user-2' },
  { id: 'user-3', username: 'Charlie', avatarUrl: 'https://i.pravatar.cc/150?u=user-3' },
];

export const coupons: Coupon[] = [
  {
    id: 'coupon-1',
    title: '50% off at The Coffee House',
    description: 'Enjoy a half-price latte or cappuccino. One-time use.',
    originalPrice: 5.0,
    sellingPrice: 1.0,
    expirationDate: formatISO(subDays(new Date(), -10)),
    couponCode: 'COFFEE50',
    seller: users[1],
    postDate: formatISO(subDays(new Date(), 2)),
    imageUrl: 'https://picsum.photos/seed/1/600/400',
    imageHint: 'coffee shop',
    category: 'Food & Drink',
    isVerified: true,
    verificationConfidence: 0.95,
  },
  {
    id: 'coupon-2',
    title: '20% off at Fashion Forward',
    description: 'Get 20% off your entire purchase of new-season arrivals.',
    originalPrice: 100.0,
    sellingPrice: 5.0,
    expirationDate: formatISO(subDays(new Date(), -30)),
    couponCode: 'FASHION20',
    seller: users[0],
    postDate: formatISO(subDays(new Date(), 5)),
    imageUrl: 'https://picsum.photos/seed/2/600/400',
    imageHint: 'clothing store',
    category: 'Apparel',
    isVerified: true,
    verificationConfidence: 0.98,
  },
  {
    id: 'coupon-3',
    title: 'Buy One Get One Free Pizza',
    description: 'Buy any large pizza and get a second one of equal or lesser value for free.',
    originalPrice: 25.0,
    sellingPrice: 2.0,
    expirationDate: formatISO(subDays(new Date(), -7)),
    couponCode: 'PIZZABOGO',
    seller: users[2],
    postDate: formatISO(subDays(new Date(), 1)),
    imageUrl: 'https://picsum.photos/seed/3/600/400',
    imageHint: 'pizza restaurant',
    category: 'Food & Drink',
    isVerified: false,
    verificationConfidence: 0.6,
    verificationIssues: ['Unusually high discount for this vendor', 'Coupon code format does not match known patterns'],
  },
  {
    id: 'coupon-4',
    title: '$10 off at Bookworm\'s Paradise',
    description: 'Get $10 off any purchase over $50. Cannot be combined with other offers.',
    originalPrice: 50.0,
    sellingPrice: 1.0,
    expirationDate: formatISO(subDays(new Date(), -60)),
    couponCode: 'READMORE10',
    seller: users[1],
    postDate: formatISO(subDays(new Date(), 10)),
    imageUrl: 'https://picsum.photos/seed/4/600/400',
    imageHint: 'bookstore',
    category: 'Books & Media',
    isVerified: true,
    verificationConfidence: 0.92,
  },
  {
    id: 'coupon-5',
    title: '15% off Tech Gadgets',
    description: 'Save 15% on select electronics including headphones and smartwatches.',
    originalPrice: 200.0,
    sellingPrice: 10.0,
    expirationDate: formatISO(subDays(new Date(), -14)),
    couponCode: 'TECHDEAL15',
    seller: users[0],
    postDate: formatISO(subDays(new Date(), 3)),
    imageUrl: 'https://picsum.photos/seed/5/600/400',
    imageHint: 'electronics store',
    category: 'Electronics',
    isVerified: false,
    verificationConfidence: 0.75,
    verificationIssues: ['Expiration date is very close.'],
  },
  {
    id: 'coupon-6',
    title: 'Free Appetizer at The Grand Bistro',
    description: 'Receive a complimentary appetizer with the purchase of two main courses.',
    originalPrice: 15.0,
    sellingPrice: 3.0,
    expirationDate: formatISO(subDays(new Date(), -25)),
    couponCode: 'BISTROFREE',
    seller: users[2],
    postDate: formatISO(subDays(new Date(), 7)),
    imageUrl: 'https://picsum.photos/seed/6/600/400',
    imageHint: 'fine dining',
    category: 'Food & Drink',
    isVerified: true,
    verificationConfidence: 0.99,
  },
];

export const chats: Chat[] = [
  {
    id: 'chat-1',
    buyer: users[0],
    seller: users[1],
    coupon: { id: 'coupon-1', title: '50% off at The Coffee House' },
    messages: [
      { id: 'msg-1-1', sender: users[0], text: 'Hi, is this coupon still available?', timestamp: formatISO(subDays(new Date(), 1)) },
      { id: 'msg-1-2', sender: users[1], text: 'Yes it is!', timestamp: formatISO(subDays(new Date(), 1)) },
      { id: 'msg-1-3', sender: users[0], text: 'Great, I\'ll take it.', timestamp: formatISO(subDays(new Date(), 1)) },
    ],
  },
  {
    id: 'chat-2',
    buyer: users[2],
    seller: users[0],
    coupon: { id: 'coupon-2', title: '20% off at Fashion Forward' },
    messages: [
      { id: 'msg-2-1', sender: users[2], text: 'Would you take $4 for this coupon?', timestamp: formatISO(subDays(new Date(), 2)) },
      { id: 'msg-2-2', sender: users[0], text: 'Sure, I can do that.', timestamp: formatISO(subDays(new Date(), 2)) },
    ],
  },
];

// Assuming the logged-in user is 'Alice' (user-1)
export const loggedInUser = users[0];
